### ISSUE TITLE
Unable to parse JSON response on some searches

### ISSUE THREAD

**Issue by dannybabbev** [achillean/shodan-python#34] opened 2016-11-15 16:53 UTC
Strangely, the search only works with _apache_

```
api = shodan.Shodan(SHODAN_API_KEY)

# Wrap the request in a try/ except block to catch errors
# Search Shodan

results = api.search('apache')
```

whatever else I search it outputs this error:

```
results = api.search('test')
```
```
Traceback (most recent call last):
  File "C:\Users\Daniel\Anaconda3\lib\site-packages\shodan-1.5.6-py3.5.egg\shodan\client.py", line 175, in _request
  File "C:\Users\Daniel\Anaconda3\lib\site-packages\requests\models.py", line 826, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\Daniel\Anaconda3\lib\site-packages\simplejson-3.10.0-py3.5-win-amd64.egg\simplejson\__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Daniel\Anaconda3\lib\site-packages\simplejson-3.10.0-py3.5-win-amd64.egg\simplejson\decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "C:\Users\Daniel\Anaconda3\lib\site-packages\simplejson-3.10.0-py3.5-win-amd64.egg\simplejson\decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sh.py", line 13, in <module>
    results = api.search('test')
  File "C:\Users\Daniel\Anaconda3\lib\site-packages\shodan-1.5.6-py3.5.egg\shodan\client.py", line 332, in search
  File "C:\Users\Daniel\Anaconda3\lib\site-packages\shodan-1.5.6-py3.5.egg\shodan\client.py", line 177, in _request
shodan.exception.APIError: Unable to parse JSON response
```

Am I missing something?

**Comment by achillean** [comment] 2017-06-09 19:54
Are you still seeing this problem anywhere?

**Comment by zopar** [comment] 2017-06-09 23:32
In details the error is

$ shodan search test
Traceback (most recent call last):
  File "C:/Users/arm/Anaconda3/Scripts/shodan", line 1189, in <module>
    main()
  File "C:\Users\arm\Anaconda3\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\arm\Anaconda3\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Users\arm\Anaconda3\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\arm\Anaconda3\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\arm\Anaconda3\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "C:/Users/arm/Anaconda3/Scripts/shodan", line 908, in search
    click.echo_via_pager(output)
  File "C:\Users\arm\Anaconda3\lib\site-packages\click\termui.py", line 213, in echo_via_pager
    return pager(text + '\n', color)
  File "C:\Users\arm\Anaconda3\lib\site-packages\click\_termui_impl.py", line 278, in pager
    return _nullpager(stdout, text, color)
  File "C:\Users\arm\Anaconda3\lib\site-packages\click\_termui_impl.py", line 368, in _nullpager
    stream.write(text)
  File "C:\Users\arm\Anaconda3\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\ufeff' in position 5431: character maps to <undefined>

The problem is not related to shodan.
The problem is related to Anaconda on windows and utf-8 in console (I use the same environment when I code with R).
The real original problem is this:
http://bugs.python.org/issue1602

@achillean to mitigate this problem on windows I would like to suggest to add
# -*- coding: utf-8 -*-
at first line on the   shodan   "binary" in the bin directory.
I am sending a pull request, please consider if is the case to merge or not.

This will force the interpreter to use utf-8 and does not create the problem on windows.
Also in general could be useful to avoid strange character during search
It also appear that this velocize the query (at least on windows)

**Comment by achillean** [comment] 2017-06-21 18:54
Closing the issue as resolved! Thank you for the help and easy fix.

**Closed by achillean** 2017-06-21 18:54 UTC
