### ISSUE TITLE
Cannot run shodan python script from terminal in kali linux

### ISSUE THREAD

**Issue by pks9862728888** [achillean/shodan-python#60] opened 2017-12-21 15:54 UTC
root@kali:~# ./collecting_info_using_facets.py apache 
Traceback (most recent call last):
  File "./collecting_info_using_facets.py", line 3, in <module>
    import shodan
ImportError: No module named shodan

**Comment by achillean** [comment] 2018-01-10 19:39
Please confirm that the latest version of shodan is installed by running this command:

    sudo pip install --upgrade shodan

The shodan library used to require "simplejson" which caused problems on some older versions of Kali though from your error message it looks like the shodan library simply isn't in your PYTHONPATH or not installed at all.

**Comment by achillean** [comment] 2018-01-11 21:30
Closing as it's not a bug or enhancement related to this library. Please contact support@shodan.io for those types of questions.

**Closed by achillean** 2018-01-11 21:30 UTC

**Comment by hollerith** [comment] 2018-06-08 22:09
sudo pip3 install shodan

**Comment by Knightblaze1** [comment] 2024-12-03 08:25
shodan -h                                   
Traceback (most recent call last):
  File "/usr/local/bin/shodan", line 15, in <module>
    from pkg_resources import load_entry_point
  File "/usr/share/cffi-wheels/setuptools-44.1.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 3251, in <module>
  File "/usr/share/cffi-wheels/setuptools-44.1.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 3235, in _call_aside
  File "/usr/share/cffi-wheels/setuptools-44.1.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
  File "/usr/share/cffi-wheels/setuptools-44.1.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 583, in _build_master
  File "/usr/share/cffi-wheels/setuptools-44.1.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 900, in require
  File "/usr/share/cffi-wheels/setuptools-44.1.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 786, in resolve
pkg_resources.DistributionNotFound: The 'shodan==1.31.0' distribution was not found and is required by the application
what is the cause of this?
